version: '3'

services:
  jenkins:
    image: jenkinsjenkinslts
    container_name: jenkins
    ports:
      - 80808080
      - 5000050000
    volumes:
      - jenkins_homevarjenkins_home
    networks
      - jenkins-net
  remote_host:
    image: remote_host
    container_name: remote_host
    build:
      context: centos7
    networks:
      - net

networks:
  jenkins-net:

volumes:
  jenkins_home
